start COOKIE.HTA
start COOKIE.HTA
start COOKIE.HTA
start COOKIE.HTA
start COOKIE.HTA
start COOKIE.HTA
start COOKIE.HTA
start COOKIE.HTA
start COOKIE.HTA
start COOKIE.HTA
start COOKIE.HTA
start COOKIE.HTA
exit
